---
# spell-checker: disable
# See https://pre-commit.com/ for usage and config
repos:
    - hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
            stages:
                - commit
            types:
                - toml
          - id: check-xml
            stages:
                - commit
            types:
                - xml
          - id: check-yaml
            args:
                - --allow-multiple-documents
            stages:
                - commit
            types:
                - yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.4
      hooks:
          - id: gitleaks
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.6.4
      hooks:
          - id: ruff
          - id: ruff-format
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.4.7
      hooks:
          - id: uv-lock
          # Run the pip compile
          - id: pip-compile
            args:
                - pyproject.toml
                - -o
    - repo: https://github.com/opensource-nepal/commitlint
      rev: v1.3.0
      hooks:
          - id: commitlint
